apiVersion: v1
kind: Secret
metadata:
  name: google-secret
type: Opaque
stringData:
  # You must provide your own secret. This should be a Google Service account
  # credentials file. Fetch one at
  # https://console.cloud.google.com/iam-admin/serviceaccounts/
  credentials: >
    {
      "type": "XXXXX",
      "project_id": "XXXXX",
      "private_key_id": "XXXXX",
      "private_key": "XXXXX",
      "client_email": "XXXXX",
      "client_id": "XXXXX",
      "auth_uri": "XXXXX",
      "token_uri": "XXXXX",
      "auth_provider_x509_cert_url": "XXXXX",
      "client_x509_cert_url": "XXXXX"
    }
